# Generated by Django 4.1.3 on 2022-11-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_goods_name', models.CharField(max_length=30)),
                ('cart_goods_price', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cart_goods_quantity', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_price', models.DecimalField(decimal_places=0, max_digits=4)),
                ('goods_quantity', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
