# Generated by Django 4.1.3 on 2022-11-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods',
            new_name='Good',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_goods_name',
            new_name='CartGoodsName',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_goods_price',
            new_name='CartGoodsPrice',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_goods_quantity',
            new_name='CartGoodsQuantity',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='goods_name',
            new_name='GoodsName',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='goods_price',
            new_name='GoodsPrice',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='goods_quantity',
            new_name='GoodsQuantity',
        ),
    ]
