# Generated by Django 4.1.3 on 2022-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_goods_good_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldGoodsName', models.CharField(max_length=30)),
                ('soldGoodsPrice', models.DecimalField(decimal_places=0, max_digits=4)),
                ('soldGoodsQuantity', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
