# Generated by Django 4.1.3 on 2022-11-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sold',
            old_name='soldGoodsName',
            new_name='SoldGoodsName',
        ),
        migrations.RenameField(
            model_name='sold',
            old_name='soldGoodsPrice',
            new_name='SoldGoodsPrice',
        ),
        migrations.RenameField(
            model_name='sold',
            old_name='soldGoodsQuantity',
            new_name='SoldGoodsQuantity',
        ),
    ]
